version: '3.9'

services:
  companies-services:
    build: .
    container_name: companies-services
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DatabaseSettings__ConnectionString="Server=db;Port=5432;Database=companies;User Id=posgres;Password=posgres;"
    ports:
      - "1986:1986"

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=companies
      - POSTGRES_USER=posgres
      - POSTGRES_PASSWORD=posgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U posgres -d companies"]
      interval: 10s
      retries: 5
      start_period: 10s
