server:
  port: 1986

spring:
  jmx:
    enabled: false
  datasource:
    url: jdbc:h2:mem:companies;MODE=MSSQLServer
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  flyway:
    url: jdbc:h2:mem:companies;MODE=MSSQLServer
    user: sa
    password: sa
    baselineOnMigrate: true
    locations: classpath:db/migration
    enabled: true
    fail-on-missing-locations: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    com:
      mariano:
        companies: DEBUG
    org:
      springframework: DEBUG
    springdoc:
      documentation: INFO