CREATE SEQUENCE companies_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS companies (
    id BIGINT PRIMARY KEY DEFAULT NEXT VALUE FOR companies_seq,
    cuit VARCHAR(15) NOT NULL,
    business_name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE companies ALTER COLUMN id SET DEFAULT NEXTVAL('companies_seq');
